# Generated by Django 5.2.14 on 2026-06-02 11:36

import django.contrib.postgres.fields
import django.db.models.deletion
import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(blank=True, max_length=5000, null=True)),
                ('view_count', models.IntegerField(blank=True, default=0, null=True)),
                ('priority', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('large_number', models.BigIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('publish_time', models.TimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(blank=True, default=False, null=True)),
                ('author_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('author_inet', netfields.fields.InetAddressField(blank=True, max_length=39, null=True)),
                ('author_mac', netfields.fields.MACAddressField(blank=True, null=True)),
                ('read_duration', models.DurationField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangormtestapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('scores', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('reviewer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('reviewer_inet', netfields.fields.InetAddressField(blank=True, max_length=39, null=True)),
                ('reviewer_mac', netfields.fields.MACAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangormtestapp.article')),
            ],
        ),
    ]
